### ISSUE TITLE
万一被搜索引擎发现欺骗了他，会不会有被搜索引擎拉入黑名单的风险

### ISSUE THREAD

**Issue by hugeorange** [mydaoyuan/spa-sparender#1]

**Comment by simaoczc** [comment]
> _No description provided._

可以看[readme中的解释](https://github.com/mydaoyuan/spa-sparender#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%8A%A8%E6%80%81%E6%B8%B2%E6%9F%93%E5%88%A9%E7%94%A8-user-agent)

**Comment by mydaoyuan** [comment]
目前站点已经上线，Google 收录良好，并且静态网页内容被成功爬取了
